version: '3.8'

servvices:
  web-app:
    build: .
    image: my-web-app:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    
    environment:
      - FLASK_ENV=development


      

  

    